# Generated by Django 4.1.6 on 2023-03-03 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='person_image',
            field=models.ImageField(default='default_profile_pic.jpg', upload_to=''),
        ),
    ]
