# Generated by Django 4.1.6 on 2023-03-05 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_bookreview_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='products.articles'),
        ),
    ]
